### ISSUE TITLE
error in order of installation in manifest

### ISSUE THREAD

**Issue by bking39116** [trevorrowe/tinymce_hammer#1]
Installer throws a directory not found error on install.

Need to remove two lines (48 & 49) from manifest:

47        'plugins/advlink/link.htm',
48       'plugins/inlinepopups/editor_plugin.js',
49        'plugins/inlinepopups/editor_plugin_src.js',
59        'plugins/autoresize',

**Comment by trevorrowe** [comment]
Thank you for bringing this to my attention.  I actually added a line inbetween 47 & 48 that creates the plugins/inlinepopups directory so the to js files have a valid directory target to be copied into.  If you download the latest (patch already live) you should be able to re-run the generator.
