### ISSUE TITLE
Production issue  "DomReady is not defined"

### ISSUE THREAD

**Issue by jpgilman** [trevorrowe/tinymce_hammer#10]
Things work fine in development, but in production the editor control never renders.  Probably something stupid I'm doing, but I noticed a couple of things that suggest the problem may be deeper.  

   First, "DomReady.ready(TinymceHammer.init);" in view_helpers  throws a "DomReady is not defined" error.  
   Second, the most recent tinymce_hammer commit back in October was related to DomReady changes. 
   Third, like the previous ticket #9, /javascripts/tinymce_hammer.js doesn't appear to be generated.

**Comment by trevorrowe** [comment]
Thank you for posting the issue.  I suspect it has to do with subtle differences in how various versions of ruby handle heredoc strings.  I don't ever reference DomReady except in string in a JS context that is meant to be used by the client browser, but nevery by Ruby.  

I'll push a commit live today that removes the heredoc strings syntax in favor of plain double quoted strings.  Hopefully this will fix your issue.

**Comment by trevorrowe** [comment]
I've pushed the change live, please let me know if this does or does not resolve the issue for you.

**Comment by jpgilman** [comment]
Unfortunately it doesn't appear to resolve the issue.  I'm getting someone brighter than myself to take a look at my environment and make sure it isn't something I'm doing.  I'll get back to as soon as I know more.

**Comment by hadiS** [comment]
Hi, i have same problem on my production server. but everything works fine on my local machine. i appreciate any help

EDIT: There should be a tinymce_hammer.js file in the javascripts directory, right? Well there is one referenced in the head section of my html on my local machine but on my production server the reference to tinymce_hammer.js is empty

**Comment by hadiS** [comment]
solved

problem was the missing tinymce_hammer.js file :(

**Comment by trevorrowe** [comment]
hadiS, what is your production environment like?  The tinymce_hammer.js file is built dynamically once and then page cached to the server.  This means the file will not exist until it is requested for the 1st time and then it should live on disk.

**Comment by hadiS** [comment]
I am using apache server, ruby enterprise and phusion passenger. I don't know why, but the tinymce_hammer.js file wasn't build dynamically, so i put the one from my development environment on the server.

**Comment by trevorrowe** [comment]
It sounds like your web application process doesn't  have permission to write a file to disk.

**Comment by bkonkle** [comment]
I just posted on ticket #9 and then found this issue.  I'm definitely getting the DomReady is not defined error in my Javascript console on Chrome when I try to load the form with the tinymce fields.  As I mentioned in my previous comment, I'm running on Engine Yard behind nginx and passenger.  The web process definitely has permission to write a file to the disk - I checked.  Thanks for any help you can provide!

**Comment by bkonkle** [comment]
Yeah, the DomReady issue is definitely because the tinymce_hammer.js file is not being generated.

**Comment by trevorrowe** [comment]
I've (as noted in other issues) added a rake task you can in conjunction with your deployment that builds and caches the js file to disk.

rake tinymce:cache_js

This should resolve the issue with environments that don't build the js file.
