### ISSUE TITLE
"Couldn't find 'tinymce_hammer' generator"

### ISSUE THREAD

**Issue by rpardee** [trevorrowe/tinymce_hammer#11]
Probably I'm doing something stupid, but... following the exact instructions on http://tinymcehammer.lanalot.com/tutorials/getting_started/, I get the title error on the command line.  Should I be unzipping the archive into vendor/plugins/tinymce_hammer, or just putting the .zip there according to the instructions?

I'm running ruby 1.8.6 (2007-09-24 patchlevel 111) [i386-mswin32] and rails v2.3.4.

Thanks!

-Roy

**Comment by trevorrowe** [comment]
Sorry for the confusion.  Yeah, you need to download, then uncompress and then move the tinymce_hammer folder into vendor/plugins/.  Make sure to restart rails after you install the plugin and add the initializer.

**Comment by rpardee** [comment]
Ah, gotcha--thanks!
