### ISSUE TITLE
config/initializer/tinymce_hammer.rb file is not created  with default values.

### ISSUE THREAD

**Issue by aashish** [trevorrowe/tinymce_hammer#12]
I downloaded zip from http://tinymcehammer.lanalot.com/tutorials/getting_started/ , then uncompressed and then move the tinymce_hammer folder into vendor/plugins/
I runned
    script/generate tinymce_installation
  But,  config/initializer/tinymce_hammer.rb file is not created  with default values.

**Comment by trevorrowe** [comment]
The installer does not create one, but default values are assumed if you don't create one yourself.
