### ISSUE TITLE
in modalbox,<%=f.tinymce%> cant edit

### ISSUE THREAD

**Issue by chengdh** [trevorrowe/tinymce_hammer#15]
i use tinymce in a popup modalbox div,but the editor can't editable,why? the modalbox rails plugin (http://github.com/okonet/modalbox)

**Comment by trevorrowe** [comment]
When you add a text area the page after it has been loaded you will have to initialize the tinymce editor yourself.  You can do this by calling this small javascript snippet once the text area has been added to the page:

  TinymceHammer.addEditor('dom_id');

Just replace dom_id with the id of the html element you want converted into an editor.
