### ISSUE TITLE
Rails 3 Support?

### ISSUE THREAD

**Issue by wulftone** [trevorrowe/tinymce_hammer#16]
Great plugin!  Are there any plans to make this available in Rails 3?

**Comment by trevorrowe** [comment]
Yes, I plan to upgrade to rails 3 soon.

**Comment by tvdeyen** [comment]
+1

**Comment by trevorrowe** [comment]
I've just committed a few upgrades to the plugin.  Download and try it out, but it should be rails 3 compatible now.  There are other improvements, I'll try to upgrade the documentation soon to highlight those, but let me know if this works for you.

**Comment by wulftone** [comment]
Awesome, thanks!  I'll try it out soon.
