### ISSUE TITLE
nil.collect in Tinymce::Hammer::ViewHelpers tinymce_hammer_javascript_tags line 28

### ISSUE THREAD

**Issue by tvdeyen** [trevorrowe/tinymce_hammer#17]
init is nil if the init is not a hash. You changed the initialition of tinymce hammer from array to hash i guess. May be you should throw an error at that place like:

```
if ::Tinymce::Hammer.init.is_a?(Hash)
  init = HashWithIndifferentAccess.new(::Tinymce::Hammer.init)
  init = init.keys.sort.collect(&:to_s).sort.collect{|key|
    [key, init[key]]
  }
else
  raise 'Tinymce::Hammer.init is not a hash! Please convert your initializer file to new layout.'
end
```

**Comment by tvdeyen** [comment]
The problem is that init variable is not set if ::Tinymce::Hammer.init is not a Hash (you should update your Website btw.). You should set it like:

```
if ::Tinymce::Hammer.init.is_a?(Hash)
  init = HashWithIndifferentAccess.new(::Tinymce::Hammer.init)
  init = init.keys.sort.collect(&:to_s).sort.collect{|key|
    [key, init[key]]
  }
else
  init = ::Tinymce::Hammer.init
end
```

**Comment by trevorrowe** [comment]
Thanks for spotting the bug.  I've update the code, it should accept the old and new configuration formats properly now:

```
init = ::Tinymce::Hammer.init
if init.is_a?(Hash)
  init = HashWithIndifferentAccess.new(init)
  init = init.keys.sort.collect(&:to_s).sort.collect{|key|
    [key, init[key]]
  }
end
init = init.collect {|key,value| "#{key} : #{value.to_json}" }.join(', ')
```

The important change here is if its a hash its converted into the ordered array of key value pairs (like the old format).  The last line converts this into the javascript required for tinymce.  Let me know if this fixes your problem.

**Comment by tvdeyen** [comment]
Jupp. Working.

Thanks for the quick fix
