### ISSUE TITLE
missing paste2 plugin??

### ISSUE THREAD

**Issue by bking39116** [trevorrowe/tinymce_hammer#5]
Error thrown in server console => ActionController::RoutingError (No route matches "/javascripts/tiny_mce/plugins/paste2/editor_plugin.js" with {:method=>:get})

I used the code from Example config/initializers/tinymce_hammer.rb script on website:

2   Tinymce::Hammer.plugins = %w(safari table paste paste2 tabfocus) 

There is no paste2 in the installer or in the /public/js/tmce/plugins folders.

-bk

**Comment by bking39116** [comment]
I copied the paste folder in pub/js/tmce/ to create a paste2 folder in same place and the editor seems to be working now.

**Comment by trevorrowe** [comment]
Good eye.  The paste2 plugin is doesn't exist in the latest version of TinyMCE.  It used to be a separate plugin from paste, but its functionality has now been rolled into paste.  I've updated the readme to remove the reference to paste2.
