### ISSUE TITLE
Settings proposal

### ISSUE THREAD

**Issue by jims** [trevorrowe/tinymce_hammer#7]
Provide normal settings hashes and call `Hash#to_a` on them instead of the un-railsy settings arrays:
    Tinymce::Hammer.init = [
        [:paste_convert_headers_to_strong, true],
        [:paste_convert_middot_lists, true],
        [:paste_remove_spans, true],
        [:paste_remove_styles, true],
        [:paste_strip_class_attributes, true],
        [:theme, 'advanced'],
        [:theme_advanced_toolbar_align, 'left'],
        [:theme_advanced_toolbar_location, 'top'],
        [:theme_advanced_buttons1, 'undo,redo,cut,copy,paste,pastetext,|,bold,italic,strikethrough,blockquote,charmap,bullist,numlist,removeformat,|,link,unlink,image,|,cleanup,code'],
        [:theme_advanced_buttons2, ''],
        [:theme_advanced_buttons3, ''],
        [:valid_elements, "a[href|title],blockquote[cite],br,caption,cite,code,dl,dt,dd,em,i,img[src|alt|title|width|height|align],li,ol,p,pre,q[cite],small,strike,strong/b,sub,sup,u,ul"],
      ]

would become:

```
Tinymce::Hammer.init = {
    :paste_convert_headers_to_strong => true,
    :paste_convert_middot_lists => true,
    :paste_remove_spans => true,
    :paste_remove_styles => true,
    :paste_strip_class_attributes => true,
    :theme => 'advanced',
    :theme_advanced_toolbar_align => 'left',
    :theme_advanced_toolbar_location => 'top',
    :theme_advanced_buttons1 => 'undo,redo,cut,copy,paste,pastetext,|,bold,italic,strikethrough,blockquote,charmap,bullist,numlist,removeformat,|,link,unlink,image,|,cleanup,code',
    :theme_advanced_buttons2 => '',
    :theme_advanced_buttons3 => '',
    :valid_elements => "a[href|title],blockquote[cite],br,caption,cite,code,dl,dt,dd,em,i,img[src|alt|title|width|height|align],li,ol,p,pre,q[cite],small,strike,strong/b,sub,sup,u,ul",
}
```

Which I think is more 'the rails way' ;)

A side note would also be that passing a ruby hash to js object can easily be performed by calling the to_json method ;)

Cheers

**Comment by trevorrowe** [comment]
I personally would like to use a hash but have been forced to use the ordered array of pairs.  Why?  Rails hashes before Ruby 1.9 are not ordered.  There are quite a few TinyMCE init keys that will cause TinyMCE to fail and not load if they are set before another key (lots of the theme_advanced_.... keys are like this).  

While the hash would be nice, without requiring an ordered hash, I'm don't know a great way to preserve the order of the hash keys.

**Comment by trevorrowe** [comment]
I should add to this, sometimes the hash will work just fine, its not guaranteed to break, but for those users who have configurations that don't work with the hash (I stumbled across this bug myself) its very frustrating.  

I'll leave the issue open, as I am very open to suggestions on better ways to solve this.  I too would prefer a more standard method of setting the configuration.

**Comment by jims** [comment]
One solution would be to mimic the behaviour of the rails plugin `config.plugins = [:important_option, :all]` load order i.e. `Tinymce::Hammer.order`:

```
Tinymce::Hammer.init = {
    :paste_convert_headers_to_strong => true,
    :paste_convert_middot_lists => true,
    :paste_remove_spans => true,
    :paste_remove_styles => true,
    :paste_strip_class_attributes => true,
    :theme => 'advanced',
    :theme_advanced_toolbar_align => 'left',
    :theme_advanced_toolbar_location => 'top',
    :theme_advanced_buttons1 => 'undo,redo,cut,copy,paste,pastetext,|,bold,italic,strikethrough,blockquote,charmap,bullist,numlist,removeformat,|,link,unlink,image,|,cleanup,code',
    :theme_advanced_buttons2 => '',
    :theme_advanced_buttons3 => '',
    :valid_elements => "a[href|title],blockquote[cite],br,caption,cite,code,dl,dt,dd,em,i,img[src|alt|title|width|height|align],li,ol,p,pre,q[cite],small,strike,strong/b,sub,sup,u,ul",
}


Timemce::Hammer.order = [:valid_elements, :all]

# parsing-side
options.to_a.sort do |a, b|
  nr1 = self.order.index(a[0]).try(:"~").try(:abs) || a[0]
  nr2 = self.order.index(b[0]).try(:"~").try(:abs) || b[0]
  nr1 <=> nr2
end # or something like that xD
```

**Comment by trevorrowe** [comment]
Im working on a patch that will support both the order array of pairs and standard ruby hashes.  The hash will be sorted alphabetically by keys before converting to json.  In my limited testing this seems to eliminate the needs for another configuration value that specifies the order of hash keys.

**Comment by trevorrowe** [comment]
I've committed a patch with the upgrade for rails 3 (still works with Rails 2.3+) that adds supports for using hashes.  Let me know if this works for you or if you encounter any bugs.
