### ISSUE TITLE
NameError - undefined local variable or method `tinymce_hammer_js_path'

### ISSUE THREAD

**Issue by xtion** [trevorrowe/tinymce_hammer#8]
I am new to Ruby on Rails but am pretty good at following instructions. The install seemed to have worked fine but I get an error when viewing the page that uses <%= form.tinymce :body %> in place of <%= form.text_area :body %>. 

I get NameError: undefined local variable or method `tinymce_hammer_js_path' for #ActionView::Base:0x1247f88.

The Application Trace is:
vendor/plugins/tinymce_hammer/lib/tinymce/hammer/view_helpers.rb:28:in `tinymce_hammer_javascript_tags'

vendor/plugins/tinymce_hammer/lib/tinymce/hammer/view_helpers.rb:7:in `init_tinymce_hammer_if_required'

app/views/layouts/application.html.erb:8:in `_run_erb_47app47views47layouts47application46html46erb'

Any ideas why this might be happening. 

Thanks!

**Comment by xtion** [comment]
I got it to work at home. And yes it did only take a few minutes I feel foolish. I must have rally messed up my Ruby install at work. 

Thanks for this grate plugin.

**Comment by trevorrowe** [comment]
Good to hear.  I was looking into this and couldn't see why that would happen.
