### ISSUE TITLE
/javascripts/tinymce_hammer.js not found

### ISSUE THREAD

**Issue by danwoolley** [trevorrowe/tinymce_hammer#9]
I just downloaded the plugin and followed the instructions.  <%= init_tinymce_hammer_if_required %> is causing error "ActionView::TemplateError (undefined local variable or method `tinymce_hammer_js_path'".  I can see the route:

map.tinymce_hammer_js '/javascripts/tinymce_hammer.js', 
    :controller => 'tinymce/hammer',
    :action => 'combine'

but that tinymce_hammer.js does not exist.  Can't find it browsing through the github folders either.

**Comment by trevorrowe** [comment]
Have you restarted your server after installing the plugin?  The plugin does not provide a static js file, rather that route sends the user to a controller in the plugin's app/controller folder.  During development the combined js file is rebuilt dynamically each request.  In production environments the resulting file is cached to RAILS_ROOT/public/javascripts/tinymce_hammer.js - but only during production.

Let me know if the app restart does not fix the issue.

**Comment by bkonkle** [comment]
I'm having this problem on a site deployed at Engine Yard behind nginx/passenger.  It doesn't look like the request for /javascripts/tinymce_hammer.js is ever actually making it to Rails and the hammer controller, so the .js file is never being generated and cached.  It appears that nginx or passenger is looking on the filesystem for the .js file and returning a 404 when it's not found.  Any ideas on how to resolve?  Thanks!

**Comment by trevorrowe** [comment]
One possible fix would be to change the plugin (tinymce_hammer) so it wasn't generating the combined file and caching to disk during production.  It could pre-generate the file and require you to add it to you source control (svn/git/etc).  This would mean the file would be static in production environments.

Let me play around with it and see what kind of improvement I can make on this.  There have been a few issues with deployed environments that don't allow writing to disk (like Heroku).

**Comment by trevorrowe** [comment]
I've commited a patch that adds a rake task that combines and caches the js file to disk.  This should solve problems with odd web sever configurations that don't pass js requests through or with services like Heroku.  Just call the rake task like:

rake tinymce:cache_js

Let me know if you encounter any problems with this.
